# Permalinks
#
permalink:           pretty

# Setup
title:               K Street Media
tagline:             'Washington, DC'
description:         'A Beltway-based consultancy of media specialists with capabilities in Chicago, Manhattan, and London.'
url:                 http://kstreet.us
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              K Street Media
  url:               https://twitter.com/kstreetmedia
  email:             hello@kstreet.us

# Custom vars
version:             1.0.0

theme: jekyll-theme-cayman
