# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               K Street Media
tagline:             'Washington, D.C.'
description:         'We make clients famous.' Follow us on <a href="http://instagram.com/kstreetmedia">Instagram</a>.  
url:                 http://kstreet.us
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Pablo Manriquez
  url:               https://twitter.com/kstreetmedia
  email:             hello@kstreet.us

# Custom vars
version:             1.0.0

theme: jekyll-theme-cayman
