# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Pablo Manriquez
tagline:             'American Hopemonger'
description:         'An honest man in politics shines more there than he would elsewhere.'
url:                 http://tinyletter.com/pab
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Pablo Manriquez
  url:               https://tinyletter.com/pab
  email:             pablo@kstreet.us

# Custom vars
version:             1.0.0

theme: jekyll-theme-cayman
